### ISSUE TITLE
ghpage topのgifの内容を追加

### ISSUE THREAD

**Issue by keitakawamoto** [tkengo/hometype#39]
きっかけは、ITEigoでHtの実演紹介をしたら反応が良かったため。

gifアニメでヒントモードを紹介しているが、それ以外は [コマンドリファレンス](http://tkengo.github.io/hometype/ja/reference.html) を読まないと（gifは）出てこない。

![](http://tkengo.github.io/hometype/images/screen.gif)

トップのgifアニメの内容に`ビジュアルモード` `コマンドモード` も追加したらもっといいのではないか。
眺めてたら自然と`できること`の情報が入ってきた、という具合に。

あとストアのキャプチャにビジュアルモードも追加する（ITEigoでのPHPのコードをコピーした動作のような画面）

**Comment by keitakawamoto** [comment]
@tkengo どう思う？必要か、不要か。

**Comment by tkengo** [comment]
@keitakawamoto よいとおもうます。

**Comment by keitakawamoto** [comment]
TODO：相談の結果次回ハッカソンでスクリーンキャストを取る

**Comment by keitakawamoto** [comment]
一旦凍結
