### ISSUE TITLE
fコマンドでエラーがでる

### ISSUE THREAD

**Issue by shoyan** [tkengo/hometype#42]
fコマンドで以下のエラーがでて、リンク機能が使えない。
```
Uncaught TypeError: Failed to execute 'getComputedStyle' on 'Window': parameter 1 is not of type 'Element'.
```

`lib/dom.js` の `Dom.isVisibleInDisplay` で発生している。

最近でだした & 自分の環境特有の現象っぽい気がする。

**Comment by tacahilo** [comment]
同じくこの問題に遭遇しています．
Chromeのバージョンは Version 41.0.2272.53 beta (64-bit) です．

Developer Toolsを立ち上げた状態で `f` を押すと，`lib/dom.js`の`Dom.stayInOverflowHiddenBox`で発生しました．
具体的には119行目の `computedStyle = window.getComputedStyle(parentNode, null);`で上記と同じエラーが出ていました．

**Comment by tkengo** [comment]
お、しょーやんだけかと思ったら他の人も発生してるようですね。調べてみます。

**Comment by keitakawamoto** [comment]
Stableの最新バージョン 40.0.2214.94 (64-bit) で再現できませんでした。
おそらく、betaでのみ発生する模様？

**Comment by tkengo** [comment]
40 stable と 41 beta で `window.getComputedStyle(null, null)` を呼び出した時の挙動が変わってるぽい。

**Comment by tkengo** [comment]
あと第一引数にdocumentオブジェクトを渡した時も同じだ。
第一引数がnullでないかどうか、及びelementかどうかのチェックを追加すれば動きそう。実験だ。

**Comment by tkengo** [comment]
しょーやんの協力で、無事に動くことが確認できたので、2.1.1でストアに登録。反映まちです。

**Comment by tkengo** [comment]
@tacahilo 報告ありがとうございました〜

**Comment by keitakawamoto** [comment]
ストアに`2.1.1`反映されました。

**Comment by tacahilo** [comment]
動きました！ご対応ありがとうございましたー！！
